<?php

namespace AppBundle\Repository;

/**
 * SemaforoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SemaforoRepository extends \Doctrine\ORM\EntityRepository
{	
}
